# Generated by Django 4.0.5 on 2022-09-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_thread_delete_tread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='users',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
